/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPancakeRouter, IPancakeRouterInterface } from "../../../store/interfaces/IPancakeRouter.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "path",
        "type": "address[]"
      }
    ],
    "name": "getAmountsOut",
    "outputs": [
      {
        "internalType": "uint256[]",
        "name": "amounts",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IPancakeRouter__factory {
    static readonly abi = _abi;
    static createInterface(): IPancakeRouterInterface {
      return new Interface(_abi) as IPancakeRouterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPancakeRouter {
      return new Contract(address, _abi, runner) as unknown as IPancakeRouter;
    }
  }
  