/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as key from './Key/index.js';
export type { key };
import type * as lootbox from './Lootbox/index.js';
export type { lootbox };