/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IALFAReferralPercents, IALFAReferralPercentsInterface } from "../../../referral/interfaces/IALFAReferralPercents.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "childAddress",
        "type": "address"
      }
    ],
    "name": "getReferralPercents",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "parentAddress",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "percents",
            "type": "uint256"
          }
        ],
        "internalType": "struct ReferralPercents[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IALFAReferralPercents__factory {
    static readonly abi = _abi;
    static createInterface(): IALFAReferralPercentsInterface {
      return new Interface(_abi) as IALFAReferralPercentsInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IALFAReferralPercents {
      return new Contract(address, _abi, runner) as unknown as IALFAReferralPercents;
    }
  }
  