/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IALFAReferral__factory } from './IALFAReferral__factory.js';
export { IALFAReferralPercents__factory } from './IALFAReferralPercents__factory.js';