/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
    export type ReferralPercentsStruct = {parentAddress: AddressLike, percents: BigNumberish}

    export type ReferralPercentsStructOutput = [parentAddress: string, percents: bigint] & {parentAddress: string, percents: bigint }
  

  export interface IALFAReferralPercentsInterface extends Interface {
    getFunction(nameOrSignature: "getReferralPercents"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getReferralPercents', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getReferralPercents', data: BytesLike): Result;
  }

  

  export interface IALFAReferralPercents extends BaseContract {
    
    connect(runner?: ContractRunner | null): IALFAReferralPercents;
    waitForDeployment(): Promise<this>;

    interface: IALFAReferralPercentsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getReferralPercents: TypedContractMethod<
      [childAddress: AddressLike, ],
      [ReferralPercentsStructOutput[]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getReferralPercents'): TypedContractMethod<
      [childAddress: AddressLike, ],
      [ReferralPercentsStructOutput[]],
      'view'
    >;

    

    filters: {
      
    };
  }