/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IALFAReferral } from './IALFAReferral.js';
export type { IALFAReferralPercents } from './IALFAReferralPercents.js';