/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
    export type HolderTokenStruct = {tokenId: BigNumberish, typeId: BigNumberish}

    export type HolderTokenStructOutput = [tokenId: bigint, typeId: bigint] & {tokenId: bigint, typeId: bigint }
  

    export type TokenTypeStruct = {typeId: BigNumberish, count: BigNumberish, typeName: string, typeURI: string}

    export type TokenTypeStructOutput = [typeId: bigint, count: bigint, typeName: string, typeURI: string] & {typeId: bigint, count: bigint, typeName: string, typeURI: string }
  

  export interface IALFAKeyInterface extends Interface {
    getFunction(nameOrSignature: "addType" | "approve" | "balanceOf" | "burn" | "getApproved" | "getHolderAmounts" | "getTokens" | "getTypeAmount" | "getTypeHolderAmount" | "getTypes" | "isApprovedForAll" | "mint" | "name" | "ownerOf" | "removeType" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setApprovalForAll" | "supportsInterface" | "symbol" | "tokenType" | "tokenTypeId" | "tokenURI" | "transferFrom" | "updateType"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalForAll" | "TokenBurned" | "TokenMinted" | "Transfer" | "TypeAdded" | "TypeRemoved" | "TypeUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'addType', values: [string, string]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'burn', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getHolderAmounts', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTokens', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTypeAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTypeHolderAmount', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTypes', values?: undefined): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeType', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenType', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenTypeId', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateType', values: [BigNumberish, string, string]): string;

    decodeFunctionResult(functionFragment: 'addType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getHolderAmounts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTypeAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTypeHolderAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTypes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenTypeId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateType', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenBurnedEvent {
      export type InputTuple = [typeId: BigNumberish, holder: AddressLike, tokenId: BigNumberish, totalCount: BigNumberish];
      export type OutputTuple = [typeId: bigint, holder: string, tokenId: bigint, totalCount: bigint];
      export interface OutputObject {typeId: bigint, holder: string, tokenId: bigint, totalCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenMintedEvent {
      export type InputTuple = [typeId: BigNumberish, holder: AddressLike, tokenId: BigNumberish, totalCount: BigNumberish];
      export type OutputTuple = [typeId: bigint, holder: string, tokenId: bigint, totalCount: bigint];
      export interface OutputObject {typeId: bigint, holder: string, tokenId: bigint, totalCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TypeAddedEvent {
      export type InputTuple = [typeId: BigNumberish, typeName: string, typeURI: string];
      export type OutputTuple = [typeId: bigint, typeName: string, typeURI: string];
      export interface OutputObject {typeId: bigint, typeName: string, typeURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TypeRemovedEvent {
      export type InputTuple = [typeId: BigNumberish];
      export type OutputTuple = [typeId: bigint];
      export interface OutputObject {typeId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TypeUpdatedEvent {
      export type InputTuple = [typeId: BigNumberish, typeName: string, typeURI: string];
      export type OutputTuple = [typeId: bigint, typeName: string, typeURI: string];
      export interface OutputObject {typeId: bigint, typeName: string, typeURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IALFAKey extends BaseContract {
    
    connect(runner?: ContractRunner | null): IALFAKey;
    waitForDeployment(): Promise<this>;

    interface: IALFAKeyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addType: TypedContractMethod<
      [typeName: string, typeURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    burn: TypedContractMethod<
      [holder: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getHolderAmounts: TypedContractMethod<
      [holder: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getTokens: TypedContractMethod<
      [holder: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [[HolderTokenStructOutput[], bigint] & {count: bigint }],
      'view'
    >
    

    
    getTypeAmount: TypedContractMethod<
      [typeId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getTypeHolderAmount: TypedContractMethod<
      [holder: AddressLike, typeId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getTypes: TypedContractMethod<
      [],
      [TokenTypeStructOutput[]],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [receiver: AddressLike, typeId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    removeType: TypedContractMethod<
      [typeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenType: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [TokenTypeStructOutput],
      'view'
    >
    

    
    tokenTypeId: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateType: TypedContractMethod<
      [typeId: BigNumberish, typeName: string, typeURI: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addType'): TypedContractMethod<
      [typeName: string, typeURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [holder: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getHolderAmounts'): TypedContractMethod<
      [holder: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTokens'): TypedContractMethod<
      [holder: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [[HolderTokenStructOutput[], bigint] & {count: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTypeAmount'): TypedContractMethod<
      [typeId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTypeHolderAmount'): TypedContractMethod<
      [holder: AddressLike, typeId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTypes'): TypedContractMethod<
      [],
      [TokenTypeStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [receiver: AddressLike, typeId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeType'): TypedContractMethod<
      [typeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenType'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [TokenTypeStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'tokenTypeId'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateType'): TypedContractMethod<
      [typeId: BigNumberish, typeName: string, typeURI: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'TokenBurned'): TypedContractEvent<TokenBurnedEvent.InputTuple, TokenBurnedEvent.OutputTuple, TokenBurnedEvent.OutputObject>;
getEvent(key: 'TokenMinted'): TypedContractEvent<TokenMintedEvent.InputTuple, TokenMintedEvent.OutputTuple, TokenMintedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'TypeAdded'): TypedContractEvent<TypeAddedEvent.InputTuple, TypeAddedEvent.OutputTuple, TypeAddedEvent.OutputObject>;
getEvent(key: 'TypeRemoved'): TypedContractEvent<TypeRemovedEvent.InputTuple, TypeRemovedEvent.OutputTuple, TypeRemovedEvent.OutputObject>;
getEvent(key: 'TypeUpdated'): TypedContractEvent<TypeUpdatedEvent.InputTuple, TypeUpdatedEvent.OutputTuple, TypeUpdatedEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'TokenBurned(uint256,address,uint256,uint256)': TypedContractEvent<TokenBurnedEvent.InputTuple, TokenBurnedEvent.OutputTuple, TokenBurnedEvent.OutputObject>;
      TokenBurned: TypedContractEvent<TokenBurnedEvent.InputTuple, TokenBurnedEvent.OutputTuple, TokenBurnedEvent.OutputObject>;
    

      'TokenMinted(uint256,address,uint256,uint256)': TypedContractEvent<TokenMintedEvent.InputTuple, TokenMintedEvent.OutputTuple, TokenMintedEvent.OutputObject>;
      TokenMinted: TypedContractEvent<TokenMintedEvent.InputTuple, TokenMintedEvent.OutputTuple, TokenMintedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'TypeAdded(uint256,string,string)': TypedContractEvent<TypeAddedEvent.InputTuple, TypeAddedEvent.OutputTuple, TypeAddedEvent.OutputObject>;
      TypeAdded: TypedContractEvent<TypeAddedEvent.InputTuple, TypeAddedEvent.OutputTuple, TypeAddedEvent.OutputObject>;
    

      'TypeRemoved(uint256)': TypedContractEvent<TypeRemovedEvent.InputTuple, TypeRemovedEvent.OutputTuple, TypeRemovedEvent.OutputObject>;
      TypeRemoved: TypedContractEvent<TypeRemovedEvent.InputTuple, TypeRemovedEvent.OutputTuple, TypeRemovedEvent.OutputObject>;
    

      'TypeUpdated(uint256,string,string)': TypedContractEvent<TypeUpdatedEvent.InputTuple, TypeUpdatedEvent.OutputTuple, TypeUpdatedEvent.OutputObject>;
      TypeUpdated: TypedContractEvent<TypeUpdatedEvent.InputTuple, TypeUpdatedEvent.OutputTuple, TypeUpdatedEvent.OutputObject>;
    
    };
  }