/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from './interfaces/index.js';
export { ALFAStore__factory } from './ALFAStore__factory.js';