/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ALFALootbox__factory } from './ALFALootbox__factory.js';
export { IALFALootbox__factory } from './IALFALootbox__factory.js';